//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 09:10:50 PM AEDT 
//


package org.example.oneidschema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecurringActivityEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecurringActivityEvent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="child-activity" type="{http://www.example.org/OneIdSchema}ActivityEvent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="participation" type="{http://www.example.org/OneIdSchema}Participation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecurringActivityEvent", propOrder = {
    "childActivity",
    "participation"
})
public class RecurringActivityEvent {

    @XmlElement(name = "child-activity")
    protected List<ActivityEvent> childActivity;
    protected List<Participation> participation;

    /**
     * Gets the value of the childActivity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childActivity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivityEvent }
     * 
     * 
     */
    public List<ActivityEvent> getChildActivity() {
        if (childActivity == null) {
            childActivity = new ArrayList<ActivityEvent>();
        }
        return this.childActivity;
    }

    /**
     * Gets the value of the participation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the participation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Participation }
     * 
     * 
     */
    public List<Participation> getParticipation() {
        if (participation == null) {
            participation = new ArrayList<Participation>();
        }
        return this.participation;
    }

}
